AWSTemplateFormatVersion: 2010-09-09
Description: ASO-Choebukuro local DNS Template.

Parameters: 
  LocalDomain:
    Description: local domain name.(xxx.local)
    Type: String
    Default: aso-chiebukuro
  CWAName:
    Description: Cloud Watche Alarm Name.
    Type: String
    Default: aso-chiebukuro
  MainDBID:
    Description: Main DB instance Id
    Type: String
  MainDBIP:
    Description: Main DB instance Id
    Type: String
  SecondaryDBID:
    Description: Secondary DB instance Id
    Type: String
  SecondaryDBIP:
    Description: Secondary DB instance Id
    Type: String
  vpcId:
    Description: VPC ID
    Type: String

Resources: 
# Cloud Watche Settings
  MainDBAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: StatuCheckFailed
      Namespace: AWS/EC2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Maximum
      Threshold: 1
      ActionsEnabled: True
      AlarmDescription: MainDB Helth Check.
      AlarmName: !Join ["_" , [!Ref CWAName , Maindb ]]
      Dimensions: 
        - Name: InstanceId
          Value: !Ref MainDBID
  SecondaryDBAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: StatuCheckFailed
      Namespace: AWS/EC2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Maximum
      Threshold: 1
      ActionsEnabled: True
      AlarmDescription: SecondaryDB Helth Check.
      AlarmName: !Join ["_" , [!Ref CWAName , Secondarydb ]]
      Dimensions: 
        - Name: InstanceId
          Value: !Ref SecondaryDBID

# local Domain Settings
  route53HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref LocalDomain
      HostedZoneConfig:
        Comment: ASO-Chiebukuro VPC private hostedzone.
      VPCs:
        - VPCId: !Ref vpcId
          VPCRegion: !Sub ${AWS::Region}
  MainDBHelthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        AlarmIdentifier:
          Name: !Join ["_" , [!Ref CWAName , Maindb ]]
          Region: !Sub ${AWS::Region}
        Type: CLOUDWATCH_METRIC
        InsufficientDataHealthStatus: Unhealthy
  SecondaryDBHelthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        AlarmIdentifier:
          Name: !Join ["_" , [!Ref CWAName , Secondarydb ]]
          Region: !Sub ${AWS::Region}
        Type: CLOUDWATCH_METRIC
        InsufficientDataHealthStatus: Unhealthy
  DBRecordPrimary:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Join ["." , [ db ,!Ref LocalDomain]]
      Type: A
      TTL: 60
      Failover: PRIMARY
      HealthCheckId: !Ref MainDBHelthCheck
      HostedZoneId: !Ref route53HostedZone
      ResourceRecords: 
      - !Ref MainDBIP
      SetIdentifier: maindb
  DBRecordSecondary:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Join ["." , [ db ,!Ref LocalDomain]]
      Type: A
      TTL: 60
      Failover: SECONDARY
      HealthCheckId: !Ref SecondaryDBHelthCheck
      HostedZoneId: !Ref route53HostedZone
      ResourceRecords: 
      - !Ref SecondaryDBIP
      SetIdentifier: secondarydb