AWSTemplateFormatVersion: 2010-09-09
Description: Setiing up aso-chiebukuro environment. 

Parameters: 
  Mykeypair:
    Description: Keypair Name
    Type: AWS::EC2::KeyPair::KeyName
  S3BucketName:
    Description: S3 Backet Name
    Type: String
  LocalDomainName: 
    Description: local domain name.(xxx.local)
    Type: String
    Default: aso-chiebukuro

Resources: 
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackName: !Ref 'AWS::StackName'
      TemplateURL: ./CFn1-VPC-Template/vpc-template.yaml
  InstanceS3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./CFn1-VPC-Template/s3-instance-template.yaml
      Parameters:
        Mykey: !Ref Mykeypair
        vpcId: !GetAtt Network.Outputs.VPCID
        Pub1InstanceSubnet: !GetAtt Network.Outputs.PublicSubnet1ID
        Db1InstanceSubnet: !GetAtt Network.Outputs.PrivateSubnet1ID
        Db2InstanceSubnet: !GetAtt Network.Outputs.PrivateSubnet2ID
        S3BucketName: !Ref S3BucketName

  LocalDNS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./CFn2-LocalDNS-Template.yaml
      Parameters:
        LocalDomain: !Ref LocalDomainName
        CWAName: !Ref 'AWS::StackName'
        vpcId: !GetAtt Network.Outputs.VPCID
        MainDBID: !GetAtt InstanceS3.Outputs.MainDBInstanceID
        MainDBIP: !GetAtt InstanceS3.Outputs.SecondaryDBInstanceIP
        SecondaryDBID: !GetAtt InstanceS3.Outputs.MainDBInstanceID
        SecondaryDBIP: !GetAtt InstanceS3.Outputs.SecondaryDBInstanceIP

  ElasticBenastalk:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./CFn3-EB-Template.yaml
      Parameters:
        AppName: !Ref 'AWS::StackName'
        vpcId: !GetAtt Network.Outputs.VPCID
        PublicSubnet1: !GetAtt Network.Outputs.PublicSubnet1ID
        PublicSubnet2: !GetAtt Network.Outputs.PublicSubnet2ID
        
Outputs:
  LocalDomain:
    Description: VPC Local Domain Name
    Value: !Join [ "." , [!Ref LocalDomainName,"local"]]
    Export: 
      Name: !Join [ "-" , [!Ref 'AWS::StackName',"Local-Domain-Name"]]
  S3BucketName:
    Description: Create S3 Bucket Name
    Value: !GetAtt InstanceS3.Outputs.S3BucketName
    Export: 
      Name: !Join [ "-" , [!Ref 'AWS::StackName',"createed-Bucket-Name"]]